apiVersion: v1
kind: Pod
metadata:
  name: appdemopodone
  labels:
    app: appnode
spec:
  containers:
  - name: imagetest-node
    image: tranluong/imagetest:node
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085
