apiVersion: v1
kind: Pod
metadata:
  name: appdemopodtwo
  labels:
    app: appphp
spec:
  containers:
  - name: imagetest-php
    image: tranluong/imagetest:php
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085