apiVersion: v1
kind: Pod
metadata:
  name: appdemonginxnode
  labels:
    name: appnginxnode
spec:
  containers:
  - name: appnodeone
    image: tranluong/imagetest:node
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085
  - name: appnginxone
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
