apiVersion: v1
kind: Pod
metadata:
  name: appdemonginxnodevol
  labels:
    app: appnginxnodevol
spec:
  volumes:
    - name: "voltest"
      hostPath:
        path: "/home/html"
  containers:
  - name: appnodeone
    image: tranluong/imagetest:node
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085
    volumeMounts:
      - mountPath: /data/
        name: "voltest"

  - name: appnginxone
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: "voltest"
